version: '3.8'

services:
  backend:
    build: .
    container_name: nest-backend
    ports:
      - '4000:4000'
    environment:
      MONGO_URI: mongodb://mongo:27017/nestdb
      NODE_ENV: production
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
